### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by devlifealways** [JoyOfJavaScript/joj#3]
https://github.com/JoyOfJavaScript/joj/blob/9a3002f39c849973a6304c869a6a1119f20c1e6f/src/blockchain/src/lib/fp/data/validation2/validation.spec.mjs#L43 does not work, as **toString()** implementation will return `_Success` perhaps if you change the toString() into 
```js
class Validation {
...
  toString() {
      return `${this.constructor.name.substr(1)} (${this.#val})`
  }
}
```

**Comment by luijar** [comment]
That's odd it all seems to be working for me. Are you running the test within the Docker container? Here's what I'm seeing:

blockchain_tests_1  |   Validation:
blockchain_tests_1  |     ✔ Constructor passed
blockchain_tests_1  |     ✔ Validation#map passed
blockchain_tests_1  |     ✔ Validation#ap passed
blockchain_tests_1  |     ✔ Validation#equals passed
blockchain_tests_1  |     ✔ Validation#toString passed

I checked in my latest, please update and try again. Let me know if you still see it so I can dig into it further and thanks!

**Comment by devlifealways** [comment]
No, I'm running it outside Docker container, I'll dig into it to see if some transitive dependency is the cause. Keep up the hard work, Love what you do.

**Comment by luijar** [comment]
Thanks for the comment. Really means a lot, glad you're enjoying the book. Since you're not running the Docker instance, make sure you're the Node.js version you have in your system is at least > v12.0
